# Generated by Django 5.1.1 on 2024-11-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_timesheet_dailyentry_delete_monthlytimesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='status',
        ),
    ]
