# Generated by Django 5.1.1 on 2024-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_remove_employees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='activity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
