# Generated by Django 5.1.1 on 2024-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_alter_role_name_financemanager_hr_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='date_hired',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
