# Generated by Django 5.1.1 on 2024-11-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_alter_supervisor_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financemanager',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
