# Generated by Django 5.1.1 on 2024-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_alter_financemanager_date_hired_alter_hr_date_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='finance_manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
    ]
