# Generated by Django 5.1.1 on 2024-11-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_timesheet_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(),
        ),
    ]
