# Generated by Django 5.1.1 on 2024-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_alter_timesheet_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
