# Generated by Django 5.1.1 on 2024-11-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_timesheet_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='year',
        ),
    ]
